enum DriverActionTypes {
  GET_TRIPS_REQUEST = "GET_TRIPS_REQUEST",
  GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS",
  GET_TRIPS_ERROR = "GET_TRIPS_ERROR",

  GET_UPDATE_TRIP_REQUEST = "GET_UPDATE_TRIP_REQUEST",
  GET_UPDATE_TRIP_SUCCESS = "GET_UPDATE_TRIP_SUCCESS",
  GET_UPDATE_TRIP_ERROR = "GET_UPDATE_TRIP_ERROR",

  UPLOAD_REQUEST = "UPLOAD_REQUEST",
  UPLOAD_SUCCESS = "UPLOAD_SUCCESS",
  UPLOAD_ERROR = "UPLOAD_ERROR",

  SPECIAL_UPLOAD_REQUEST = "SPECIAL_UPLOAD_REQUEST",
  SPECIAL_UPLOAD_SUCCESS = "SPECIAL_UPLOAD_SUCCESS",
  SPECIAL_UPLOAD_ERROR = "SPECIAL_UPLOAD_ERROR",

  GET_TRIP_BY_ID_REQUEST = "GET_TRIP_BY_ID_REQUEST",
  GET_TRIP_BY_ID_SUCCESS = "GET_TRIP_BY_ID_SUCCESS",
  GET_TRIP_BY_ID_ERROR = "GET_TRIP_BY_ID_ERROR"
}

export default DriverActionTypes;
