enum DriverActionTypes {
  GET_TRIPS_REQUEST = "GET_TRIPS_REQUEST",
  GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS",
  GET_TRIPS_ERROR = "GET_TRIPS_ERROR",

  GET_UPDATE_TRIP_REQUEST = "GET_UPDATE_TRIP_REQUEST",
  GET_UPDATE_TRIP_SUCCESS = "GET_UPDATE_TRIP_SUCCESS",
  GET_UPDATE_TRIP_ERROR = "GET_UPDATE_TRIP_ERROR"
}

export default DriverActionTypes;
