enum ActionTypes {
  SEND_OTP_REQUEST = "SEND_OTP_REQUEST",
  SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS",
  SEND_OTP_ERROR = "SEND_OTP_ERROR",

  VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST",
  VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR",

  RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST",
  RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS",
  RESEND_OTP_ERROR = "RESEND_OTP_ERROR",

  SAVE_PROFILE_REQUEST = "SAVE_PROFILE_REQUEST",
  SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS",
  SAVE_PROFILE_ERROR = "SAVE_PROFILE_ERROR",

  SAVE_COMPANY_PROFILE_REQUEST = "SAVE_COMPANY_PROFILE_REQUEST",
  SAVE_COMPANY_PROFILE_SUCCESS = "SAVE_COMPANY_PROFILE_SUCCESS",
  SAVE_COMPANY_PROFILE_ERROR = "SAVE_COMPANY_PROFILE_ERROR",

  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_ERROR = "LOGIN_ERROR",

  LOGOUT = "LOGOUT",

  GET_TRIPS_REQUEST = "GET_TRIPS_REQUEST",
  GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS",
  GET_TRIPS_ERROR = "GET_TRIPS_ERROR",

  HOME_METRICS_REQUEST = "HOME_METRICS_REQUEST",
  HOME_METRICS_SUCCESS = "HOME_METRICS_SUCCESS",
  HOME_METRICS_ERROR = "HOME_METRICS_ERROR",

  CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST",
  CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS",
  CREATE_TRIP_ERROR = "CREATE_TRIP_ERROR",

  LSP_LIST_REQUEST = "LSP_LIST_REQUEST",
  LSP_LIST_SUCCESS = "LSP_LIST_SUCCESS",
  LSP_LIST_ERROR = "LSP_LIST_ERROR",

  APP_CONFIG_REQUEST = "APP_CONFIG_REQUEST",
  APP_CONFIG_SUCCESS = "APP_CONFIG_SUCCESS",
  APP_CONFIG_ERROR = "APP_CONFIG_ERROR",

  SAVE_TRUCK_REQUEST = "SAVE_TRUCK_REQUEST",
  SAVE_TRUCK_SUCCESS = "SAVE_TRUCK_SUCCESS",
  SAVE_TRUCK_ERROR = "SAVE_TRUCK_ERROR",

  VEHICLES_LIST_REQUEST = "VEHICLES_LIST_REQUEST",
  VEHICLES_LIST_SUCCESS = "VEHICLES_LIST_SUCCESS",
  VEHICLES_LIST_ERROR = "VEHICLES_LIST_ERROR",

  GET_BUSINESS_SITES_REQUEST = "GET_BUSINESS_SITES_REQUEST",
  GET_BUSINESS_SITES_SUCCESS = "GET_BUSINESS_SITES_SUCCESS",
  GET_BUSINESS_SITES_ERROR = "GET_BUSINESS_SITES_ERROR",

  SET_USER_PERSONA = "SET_USER_PERSONA",

  SET_USER_LANGUAGE = "SET_USER_LANGUAGE",

  SAVE_WAREHOUSE_REQUEST = "SAVE_WAREHOUSE_REQUEST",
  SAVE_WAREHOUSE_SUCCESS = "SAVE_WAREHOUSE_SUCCESS",
  SAVE_WAREHOUSE_ERROR = "SAVE_WAREHOUSE_ERROR",

  GET_DRIVER_TRIPS_REQUEST = "GET_DRIVER_TRIPS_REQUEST",
  GET_DRIVER_TRIPS_SUCCESS = "GET_DRIVER_TRIPS_SUCCESS",
  GET_DRIVER_TRIPS_ERROR = "GET_DRIVER_TRIPS_ERROR",

  GET_UPDATE_TRIP_REQUEST = "GET_UPDATE_TRIP_REQUEST",
  GET_UPDATE_TRIP_SUCCESS = "GET_UPDATE_TRIP_SUCCESS",
  GET_UPDATE_TRIP_ERROR = "GET_UPDATE_TRIP_ERROR",

  UPLOAD_REQUEST = "UPLOAD_REQUEST",
  UPLOAD_SUCCESS = "UPLOAD_SUCCESS",
  UPLOAD_ERROR = "UPLOAD_ERROR",

  SPECIAL_UPLOAD_REQUEST = "SPECIAL_UPLOAD_REQUEST",
  SPECIAL_UPLOAD_SUCCESS = "SPECIAL_UPLOAD_SUCCESS",
  SPECIAL_UPLOAD_ERROR = "SPECIAL_UPLOAD_ERROR",

  GET_TRIP_BY_ID_REQUEST = "GET_TRIP_BY_ID_REQUEST",
  GET_TRIP_BY_ID_SUCCESS = "GET_TRIP_BY_ID_SUCCESS",
  GET_TRIP_BY_ID_ERROR = "GET_TRIP_BY_ID_ERROR",

  TRIP_ACCEPT_REQUEST = "TRIP_ACCEPT_REQUEST",
  TRIP_ACCEPT_SUCCESS = "TRIP_ACCEPT_SUCCESS",
  TRIP_ACCEPT_ERROR = "TRIP_ACCEPT_ERROR",

  TRIP_REJECT_REQUEST = "TRIP_REJECT_REQUEST",
  TRIP_REJECT_SUCCESS = "TRIP_REJECT_SUCCESS",
  TRIP_REJECT_ERROR = "TRIP_REJECT_ERROR",

  ADD_EWAYBILL_REQUEST = "ADD_EWAYBILL_REQUEST",
  ADD_EWAYBILL_SUCCESS = "ADD_EWAYBILL_SUCCES",
  ADD_EWAYBILL_ERROR = "ADD_EWAYBILL_ERROR",

  GENERATE_EWAYBILL_REQUEST = "GENERATE_EWAYBILL_REQUEST",
  GENERATE_EWAYBILL_SUCCESS = "GENERATE_EWAYBILL_SUCCESS",
  GENERATE_EWAYBILL_ERROR = "GENERATE_EWAYBILL_ERROR"
}

export default ActionTypes;
