enum ShipperActionTypes {
  CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST",
  CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS",
  CREATE_TRIP_ERROR = "CREATE_TRIP_ERROR"
}

export default ShipperActionTypes;
