enum ShipperActionTypes {
  CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST",
  CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS",
  CREATE_TRIP_ERROR = "CREATE_TRIP_ERROR",

  LSP_LIST_REQUEST = "LSP_LIST_REQUEST",
  LSP_LIST_SUCCESS = "LSP_LIST_SUCCESS",
  LSP_LIST_ERROR = "LSP_LIST_ERROR"
}

export default ShipperActionTypes;
