enum LSPActionTypes {
  TRIP_ACCEPT_REQUEST = "TRIP_ACCEPT_REQUEST",
  TRIP_ACCEPT_SUCCESS = "TRIP_ACCEPT_SUCCESS",
  TRIP_ACCEPT_ERROR = "TRIP_ACCEPT_ERROR",

  TRIP_REJECT_REQUEST = "TRIP_REJECT_REQUEST",
  TRIP_REJECT_SUCCESS = "TRIP_REJECT_SUCCESS",
  TRIP_REJECT_ERROR = "TRIP_REJECT_ERROR"
}

export default LSPActionTypes;
