// dont edit this as this is autogenerated
// its generated from translation-types.js
export type Keys =
  | "are.you.sure"
  | "capture.pop"
  | "choose.reason"
  | "choose.truck"
  | "close"
  | "company.setup"
  | "confirm"
  | "current.profile"
  | "destination.point"
  | "does.not.exist"
  | "driver.details"
  | "driver.name"
  | "go.back"
  | "go.to.map"
  | "i.am.driver"
  | "i.am.lsp"
  | "i.am.shipper"
  | "india.prefix"
  | "it.will.be.enabled"
  | "lsp"
  | "mobile.number"
  | "no.trips"
  | "on.road"
  | "other.profiles"
  | "otp.sent"
  | "otp.verified"
  | "pending"
  | "pick.up.date"
  | "pick.up.point"
  | "placeholder"
  | "profile.setup"
  | "reached"
  | "reject"
  | "requests"
  | "required.weight"
  | "rice.grain.wheat"
  | "setup.required"
  | "start.trip"
  | "swipe.to.start"
  | "tell.us.about"
  | "this.helps.to.personalize"
  | "trip.details"
  | "trip.id"
  | "trip.tracking.not.available"
  | "truck.type"
  | "trucks"
  | "uploaded.docs"
  | "verifying"
  | "choose.language"
  | "continue"
  | "proof.of.delivery.tnc.received";
export type GetTranslationTextType<T> = T extends "are.you.sure"
  ? never
  : T extends "capture.pop"
  ? never
  : T extends "choose.reason"
  ? never
  : T extends "choose.truck"
  ? never
  : T extends "close"
  ? never
  : T extends "company.setup"
  ? never
  : T extends "confirm"
  ? never
  : T extends "current.profile"
  ? never
  : T extends "destination.point"
  ? never
  : T extends "does.not.exist"
  ? never
  : T extends "driver.details"
  ? never
  : T extends "driver.name"
  ? never
  : T extends "go.back"
  ? never
  : T extends "go.to.map"
  ? never
  : T extends "i.am.driver"
  ? never
  : T extends "i.am.lsp"
  ? never
  : T extends "i.am.shipper"
  ? never
  : T extends "india.prefix"
  ? never
  : T extends "it.will.be.enabled"
  ? { date: string }
  : T extends "lsp"
  ? never
  : T extends "mobile.number"
  ? never
  : T extends "no.trips"
  ? never
  : T extends "on.road"
  ? never
  : T extends "other.profiles"
  ? never
  : T extends "otp.sent"
  ? never
  : T extends "otp.verified"
  ? { phoneNumber: string }
  : T extends "pending"
  ? never
  : T extends "pick.up.date"
  ? never
  : T extends "pick.up.point"
  ? never
  : T extends "placeholder"
  ? { value: string }
  : T extends "profile.setup"
  ? never
  : T extends "reached"
  ? never
  : T extends "reject"
  ? never
  : T extends "requests"
  ? never
  : T extends "required.weight"
  ? never
  : T extends "rice.grain.wheat"
  ? never
  : T extends "setup.required"
  ? never
  : T extends "start.trip"
  ? never
  : T extends "swipe.to.start"
  ? never
  : T extends "tell.us.about"
  ? never
  : T extends "this.helps.to.personalize"
  ? never
  : T extends "trip.details"
  ? never
  : T extends "trip.id"
  ? never
  : T extends "trip.tracking.not.available"
  ? never
  : T extends "truck.type"
  ? never
  : T extends "trucks"
  ? never
  : T extends "uploaded.docs"
  ? never
  : T extends "verifying"
  ? never
  : T extends "choose.language"
  ? never
  : T extends "continue"
  ? never
  : T extends "proof.of.delivery.tnc.received"
  ? never
  : never;
