// dont edit this as this is autogenerated
// its generated from translation-types.js
export type Keys =
  | "accept.terms"
  | "account"
  | "accounts"
  | "add.now"
  | "add.warehouse"
  | "address"
  | "are.you.sure"
  | "capture.pop"
  | "choose.language"
  | "choose.lsp"
  | "choose.reason"
  | "choose.truck"
  | "choose.unit"
  | "city"
  | "close"
  | "company.name"
  | "company.setup"
  | "confirm"
  | "container"
  | "continue"
  | "create.trip"
  | "current.profile"
  | "destination.point"
  | "details"
  | "do.not.have.ewb"
  | "does.not.exist"
  | "driver.details"
  | "driver.name"
  | "error"
  | "errors.name"
  | "errors.regNumber"
  | "errors.regNumber.maxlength"
  | "errors.gstin"
  | "errors.gstin.invalid"
  | "errors.location"
  | "errors.pinCode"
  | "errors.address"
  | "errors.city"
  | "errors.state"
  | "errors.warehouseName"
  | "eway.error"
  | "eway.loading"
  | "eway.password"
  | "eway.pending"
  | "eway.success"
  | "eway.username"
  | "failed.to.fetch.trip.details"
  | "from"
  | "generate.ewb"
  | "go.back"
  | "go.to.map"
  | "gps.id"
  | "gps.vendor"
  | "gstin.label"
  | "history"
  | "home"
  | "i.am.driver"
  | "i.am.lsp"
  | "i.am.shipper"
  | "in.transit"
  | "india.prefix"
  | "it.will.be.enabled"
  | "loading"
  | "locate.on.map"
  | "lsp"
  | "mobile.number"
  | "modify.request"
  | "must.have.ewb"
  | "next"
  | "no.business.id"
  | "no.trips"
  | "no.upcoming.trips"
  | "on.road"
  | "open"
  | "other.profiles"
  | "otp.not.received"
  | "otp.resend.failed"
  | "otp.resent"
  | "otp.sent"
  | "otp.verified"
  | "pending"
  | "pending.literally"
  | "pick.up.date"
  | "pick.up.point"
  | "pincode"
  | "placeholder"
  | "please.wait"
  | "preference"
  | "preview"
  | "profile.setup"
  | "proof.of.delivery.tnc.received"
  | "raise.request"
  | "reached"
  | "registration.number"
  | "reject"
  | "requested"
  | "requests"
  | "required.weight"
  | "resend"
  | "rice.grain.wheat"
  | "save.company"
  | "save.truck"
  | "save.warehouse"
  | "save.warehouse.failed"
  | "saved.warehouse"
  | "saving"
  | "select.goods.type"
  | "select.location"
  | "send.request"
  | "setup.required"
  | "signature"
  | "start"
  | "start.trip"
  | "state"
  | "submit"
  | "swipe.to.start"
  | "tell.us.about"
  | "this.helps.to.personalize"
  | "trip.details"
  | "trip.id"
  | "trip.tracking.not.available"
  | "trolley"
  | "truck.details"
  | "truck.location"
  | "truck.name"
  | "truck.number"
  | "truck.save.error"
  | "truck.save.success"
  | "truck.type"
  | "trucks"
  | "try.again"
  | "upcoming"
  | "uploaded.docs"
  | "valid.upto"
  | "verifying"
  | "warehouse.details"
  | "warehouse.name";
export type GetTranslationTextType<T> = T extends "accept.terms"
  ? never
  : T extends "account"
  ? never
  : T extends "accounts"
  ? never
  : T extends "add.now"
  ? never
  : T extends "add.warehouse"
  ? never
  : T extends "address"
  ? never
  : T extends "are.you.sure"
  ? never
  : T extends "capture.pop"
  ? never
  : T extends "choose.language"
  ? never
  : T extends "choose.lsp"
  ? never
  : T extends "choose.reason"
  ? never
  : T extends "choose.truck"
  ? never
  : T extends "choose.unit"
  ? never
  : T extends "city"
  ? never
  : T extends "close"
  ? never
  : T extends "company.name"
  ? never
  : T extends "company.setup"
  ? never
  : T extends "confirm"
  ? never
  : T extends "container"
  ? never
  : T extends "continue"
  ? never
  : T extends "create.trip"
  ? never
  : T extends "current.profile"
  ? never
  : T extends "destination.point"
  ? never
  : T extends "details"
  ? never
  : T extends "do.not.have.ewb"
  ? never
  : T extends "does.not.exist"
  ? never
  : T extends "driver.details"
  ? never
  : T extends "driver.name"
  ? never
  : T extends "error"
  ? never
  : T extends "errors.name"
  ? never
  : T extends "errors.regNumber"
  ? never
  : T extends "errors.regNumber.maxlength"
  ? never
  : T extends "errors.gstin"
  ? never
  : T extends "errors.gstin.invalid"
  ? never
  : T extends "errors.location"
  ? never
  : T extends "errors.pinCode"
  ? never
  : T extends "errors.address"
  ? never
  : T extends "errors.city"
  ? never
  : T extends "errors.state"
  ? never
  : T extends "errors.warehouseName"
  ? never
  : T extends "eway.error"
  ? never
  : T extends "eway.loading"
  ? never
  : T extends "eway.password"
  ? never
  : T extends "eway.pending"
  ? never
  : T extends "eway.success"
  ? never
  : T extends "eway.username"
  ? never
  : T extends "failed.to.fetch.trip.details"
  ? never
  : T extends "from"
  ? never
  : T extends "generate.ewb"
  ? never
  : T extends "go.back"
  ? never
  : T extends "go.to.map"
  ? never
  : T extends "gps.id"
  ? never
  : T extends "gps.vendor"
  ? never
  : T extends "gstin.label"
  ? never
  : T extends "history"
  ? never
  : T extends "home"
  ? never
  : T extends "i.am.driver"
  ? never
  : T extends "i.am.lsp"
  ? never
  : T extends "i.am.shipper"
  ? never
  : T extends "in.transit"
  ? never
  : T extends "india.prefix"
  ? never
  : T extends "it.will.be.enabled"
  ? { date: string }
  : T extends "loading"
  ? never
  : T extends "locate.on.map"
  ? never
  : T extends "lsp"
  ? never
  : T extends "mobile.number"
  ? never
  : T extends "modify.request"
  ? never
  : T extends "must.have.ewb"
  ? never
  : T extends "next"
  ? never
  : T extends "no.business.id"
  ? never
  : T extends "no.trips"
  ? never
  : T extends "no.upcoming.trips"
  ? never
  : T extends "on.road"
  ? never
  : T extends "open"
  ? never
  : T extends "other.profiles"
  ? never
  : T extends "otp.not.received"
  ? never
  : T extends "otp.resend.failed"
  ? never
  : T extends "otp.resent"
  ? never
  : T extends "otp.sent"
  ? never
  : T extends "otp.verified"
  ? { phoneNumber: string }
  : T extends "pending"
  ? never
  : T extends "pending.literally"
  ? never
  : T extends "pick.up.date"
  ? never
  : T extends "pick.up.point"
  ? never
  : T extends "pincode"
  ? never
  : T extends "placeholder"
  ? { value: string }
  : T extends "please.wait"
  ? never
  : T extends "preference"
  ? never
  : T extends "preview"
  ? never
  : T extends "profile.setup"
  ? never
  : T extends "proof.of.delivery.tnc.received"
  ? never
  : T extends "raise.request"
  ? never
  : T extends "reached"
  ? never
  : T extends "registration.number"
  ? never
  : T extends "reject"
  ? never
  : T extends "requested"
  ? never
  : T extends "requests"
  ? never
  : T extends "required.weight"
  ? never
  : T extends "resend"
  ? never
  : T extends "rice.grain.wheat"
  ? never
  : T extends "save.company"
  ? never
  : T extends "save.truck"
  ? never
  : T extends "save.warehouse"
  ? never
  : T extends "save.warehouse.failed"
  ? never
  : T extends "saved.warehouse"
  ? never
  : T extends "saving"
  ? never
  : T extends "select.goods.type"
  ? never
  : T extends "select.location"
  ? never
  : T extends "send.request"
  ? never
  : T extends "setup.required"
  ? never
  : T extends "signature"
  ? never
  : T extends "start"
  ? never
  : T extends "start.trip"
  ? never
  : T extends "state"
  ? never
  : T extends "submit"
  ? never
  : T extends "swipe.to.start"
  ? never
  : T extends "tell.us.about"
  ? never
  : T extends "this.helps.to.personalize"
  ? never
  : T extends "trip.details"
  ? never
  : T extends "trip.id"
  ? never
  : T extends "trip.tracking.not.available"
  ? never
  : T extends "trolley"
  ? never
  : T extends "truck.details"
  ? never
  : T extends "truck.location"
  ? never
  : T extends "truck.name"
  ? never
  : T extends "truck.number"
  ? never
  : T extends "truck.save.error"
  ? never
  : T extends "truck.save.success"
  ? never
  : T extends "truck.type"
  ? never
  : T extends "trucks"
  ? never
  : T extends "try.again"
  ? never
  : T extends "upcoming"
  ? never
  : T extends "uploaded.docs"
  ? never
  : T extends "valid.upto"
  ? never
  : T extends "verifying"
  ? never
  : T extends "warehouse.details"
  ? never
  : T extends "warehouse.name"
  ? never
  : never;
