// dont edit this as this is autogenerated
// its generated from translation-types.js
export type Keys = "hi" | "mobile" | "bye";
export type GetTranslationTextType<T> = T extends "hi"
  ? never
  : T extends "mobile"
  ? never
  : T extends "bye"
  ? { name: string }
  : never;
